### ISSUE TITLE
Syntax Highlight does not get changed on gedit 2.26.1 ubuntu 9.04

### ISSUE THREAD

**Issue by azendal** [nagaozen/gedit-plugin-quickhighlightmode#1]
Hi i can see the plugin, and all seems to work but does not affect gedit's syntax highlighting mode, and, because of that dialog does not get closed after selection

**Comment by nagaozen** [comment]
Just re-re-checked it and it's fine... This bug is old and it's already fixed in the HEAD version, please download and install again.

**Comment by azendal** [comment]
thanks ill download again
